const CONFIG = globalThis.PORTFOLIO_CONFIG;
const { profiles, projects, certificates } = CONFIG;
const fallbackStats = { leetcode: { solved: 100 }, codechef: { solved: 1000 }, gfg: { solved: 250 }, updatedAt: "Fallback values" };
const skills = { "Programming Languages": ["Java", "C", "C++", "Python", "HTML", "CSS", "SQL"], "Android Development": ["Android (Java, XML)", "Figma"], "Backend Development": ["Spring Boot", "Spring Data JPA"], "Databases": ["MySQL", "Firebase Realtime Database", "Cloud Firestore"], "Tools & Technologies": ["Git", "GitHub", "Postman", "Oracle Cloud (OCI)"], "Core Concepts": ["DSA", "OOP", "Operating Systems", "SDLC", "Computer Networks", "Cloud Computing"] };
const $ = (selector) => document.querySelector(selector);
const external = (url, label, content) => `<a href="${url}" target="_blank" rel="noopener noreferrer" aria-label="${label}">${content}</a>`;

function renderContent() {
  $("#skills-grid").innerHTML = Object.entries(skills).map(([name, items]) => `<article class="skill-card reveal"><h3>${name}</h3><div class="skill-list">${items.map((item) => `<span>${item}</span>`).join("")}</div></article>`).join("");
  $("#projects-grid").innerHTML = projects.map((project, index) => `<article class="project-card reveal"><span class="project-index">0${index + 1} / PROJECT</span><h3>${external(project.link, `View ${project.title} repository on GitHub`, project.title)}</h3>${project.subtitle ? `<p class="project-date">${project.subtitle}</p>` : ""}<p class="project-date">${project.date}</p><p>${project.description}</p><div class="tag-list">${project.tech.map((tag) => `<span class="tag">${tag}</span>`).join("")}</div>${external(project.link, `View ${project.title} source code on GitHub`, "View on GitHub ↗")}</article>`).join("");
  $("#all-projects-link").innerHTML = external(profiles.github, "View all Swati Patil projects on GitHub", "View all projects on GitHub ↗");
  $("#certificates-grid").innerHTML = certificates.map((certificate) => `<article class="certificate-card reveal"><div><h3>${certificate.title}</h3><small>${certificate.issuer}</small><p class="credential">${external(certificate.link, `View ${certificate.title} credential ${certificate.id}`, `ID: ${certificate.id}`)}</p></div>${external(certificate.link, `View ${certificate.title} certificate`, "View Certificate ↗")}</article>`).join("");
  $("#hero-socials").innerHTML = [external(profiles.github, "Visit Swati Patil on GitHub", "GH"), external(profiles.linkedin, "Connect with Swati Patil on LinkedIn", "in"), external(profiles.leetcode, "View Swati Patil on LeetCode", "LC"), external(profiles.codechef, "View Swati Patil on CodeChef", "CC"), external(profiles.gfg, "View Swati Patil on GeeksforGeeks", "GFG"), external(profiles.email, "Email Swati Patil", "@")].join("");
  $("#nav-socials").innerHTML = [external(profiles.github, "Visit Swati Patil on GitHub", "GH"), external(profiles.linkedin, "Connect with Swati Patil on LinkedIn", "in")].join("");
  $("#about-links").innerHTML = [external(profiles.github, "Visit Swati Patil on GitHub", "GitHub ↗"), external(profiles.linkedin, "Connect with Swati Patil on LinkedIn", "LinkedIn ↗")].join("");
  $("#contact-details").innerHTML = [external(profiles.email, "Email Swati Patil", "<span>@</span>swatiipatil12@gmail.com"), external(profiles.phone, "Call Swati Patil", "<span>✆</span>+91 98234 68176"), external(profiles.linkedin, "Connect with Swati Patil on LinkedIn", "<span>in</span>LinkedIn"), external(profiles.github, "Visit Swati Patil on GitHub", "<span>GH</span>GitHub"), `<span><span>⌖</span>Kolhapur, Maharashtra</span>`].join("");
  $("#footer-links").innerHTML = [external(profiles.github, "Visit Swati Patil on GitHub", "GitHub"), external(profiles.linkedin, "Connect with Swati Patil on LinkedIn", "LinkedIn"), external(profiles.leetcode, "View Swati Patil on LeetCode", "LeetCode"), external(profiles.codechef, "View Swati Patil on CodeChef", "CodeChef"), external(profiles.gfg, "View Swati Patil on GeeksforGeeks", "GFG"), external(profiles.email, "Email Swati Patil", "Email"), external(profiles.phone, "Call Swati Patil", "Phone")].join("");
  $("#badges").innerHTML = `<article class="badge-card reveal">${external(CONFIG.badges.googleCloud, "View Google Cloud Skill Badge", '<span class="badge-mark">G</span><div><small>Google Cloud Skill Badge</small><h3>Prepare Data for ML APIs on Google Cloud</h3><p>Introductory · View Badge ↗</p></div>')}</article><article class="badge-card reveal">${external(CONFIG.badges.codechef, "View CodeChef 1000+ Problem Solving Badge", '<span class="badge-mark">C</span><div><small>CodeChef badge</small><h3>1000+ Problem Solving</h3><p>Competitive programming · View Badge ↗</p></div>')}</article>`;
  $("#resume-link").href = CONFIG.resume;
}

function setupNavigation() {
  const menu = $("#nav-links");
  $(".menu-toggle").addEventListener("click", () => { const open = menu.classList.toggle("open"); $(".menu-toggle").setAttribute("aria-expanded", open); });
  menu.querySelectorAll("a").forEach((link) => link.addEventListener("click", () => menu.classList.remove("open")));
  $(".theme-toggle").addEventListener("click", () => { document.documentElement.classList.toggle("light"); localStorage.setItem("portfolio-theme", document.documentElement.classList.contains("light") ? "light" : "dark"); $(".theme-icon").textContent = document.documentElement.classList.contains("light") ? "☀" : "☾"; });
  if (localStorage.getItem("portfolio-theme") === "light") { document.documentElement.classList.add("light"); $(".theme-icon").textContent = "☀"; }
  const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) document.querySelectorAll(".nav-links > a").forEach((link) => link.classList.toggle("active", link.getAttribute("href") === `#${entry.target.id}`)); }), { rootMargin: "-35% 0px -55%" });
  document.querySelectorAll("main section[id]").forEach((section) => observer.observe(section));
}

function setupReveal() { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add("visible"); observer.unobserve(entry.target); } }), { threshold: .12 }); document.querySelectorAll(".reveal").forEach((element, index) => { element.style.transitionDelay = `${Math.min(index % 5, 4) * 60}ms`; observer.observe(element); }); }
function setupScrollEffects() { const ring = $(".progress-ring"); const circumference = 119.4; window.addEventListener("scroll", () => { const max = document.documentElement.scrollHeight - innerHeight; const progress = max ? scrollY / max : 0; $("#scroll-progress").style.width = `${progress * 100}%`; $("#to-top").classList.toggle("visible", scrollY > 300); ring.style.strokeDashoffset = circumference * (1 - progress); }, { passive: true }); $("#to-top").addEventListener("click", () => window.scrollTo({ top: 0, behavior: "smooth" })); }
function setupTyping() { const words = ["Java Developer", "Backend Engineer", "Android Developer"]; let word = 0; let position = 0; let deleting = false; const element = $("#typing-text"); const tick = () => { const current = words[word]; element.textContent = current.slice(0, position); if (!deleting && position < current.length) position++; else if (deleting && position > 0) position--; else { deleting = !deleting; if (!deleting) word = (word + 1) % words.length; } setTimeout(tick, deleting ? 45 : position === current.length ? 1600 : 85); }; tick(); }

function renderStats(stats) {
  const platforms = [{ key: "leetcode", name: "LeetCode", url: profiles.leetcode }, { key: "codechef", name: "CodeChef", url: profiles.codechef }, { key: "gfg", name: "GeeksforGeeks", url: profiles.gfg }];
  $("#stats-grid").innerHTML = platforms.map(({ key, name, url }) => { const value = stats[key]?.solved; const unavailable = value === null || value === undefined; return `<a class="stat-card reveal ${unavailable ? "unavailable" : ""}" href="${url}" target="_blank" rel="noopener noreferrer" aria-label="View Swati Patil's ${name} profile"><span class="stat-label">${name}</span><strong class="stat-number" data-count="${unavailable ? 0 : value}">${unavailable ? "—" : "0"}${value >= 1000 ? "+" : ""}</strong><span class="stat-meta">${unavailable ? "Stats unavailable" : `Updated ${stats.updatedAt ? new Date(stats.updatedAt).toLocaleDateString() : "recently"} · View Profile ↗`}</span></a>`; }).join("");
  document.querySelectorAll(".stat-number[data-count]").forEach((element) => { const target = Number(element.dataset.count); let started = false; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting && !started) { started = true; let current = 0; const step = Math.max(1, Math.ceil(target / 35)); const count = () => { current = Math.min(current + step, target); element.textContent = `${current}${target >= 1000 ? "+" : ""}`; if (current < target) requestAnimationFrame(count); }; count(); observer.disconnect(); } }); observer.observe(element); }); setupReveal();
}

function loadConfig() { if (!CONFIG.formspreeEndpoint.includes("PASTE_FORMSPREE")) $("#contact-form").action = `https://formspree.io/f/${CONFIG.formspreeEndpoint}`; }
async function loadStats() { loadConfig(); try { const response = await fetch("data/stats.json", { cache: "no-store" }); if (!response.ok) throw new Error("Stats unavailable"); renderStats(await response.json()); } catch { renderStats(fallbackStats); } }
$("#contact-form").addEventListener("submit", (event) => { if (CONFIG.formspreeEndpoint.includes("PASTE_FORMSPREE")) { event.preventDefault(); $(".form-status").textContent = "Add your Formspree endpoint in data/config.js to enable submissions."; } });
renderContent(); setupNavigation(); setupReveal(); setupScrollEffects(); setupTyping(); loadStats();
